version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py

python:
  version: 3.13     # This sets the Python version for dependency installation
  install:
    - requirements: docs/requirements.txt
