version: 2

build:
  os: "ubuntu-22.04"  # or "ubuntu-20.04"
  tools:
    python: "3.11"    # sets Python version

sphinx:
  configuration: docs/conf.py

python:
  system_packages: false
  install:
    - requirements: docs/requirements.txt
